"""
KarenAI package — autonomous legal passenger rights assistant.
"""

from karenai.config import (
    AIRLINES,
    APP_TAGLINE,
    APP_TITLE,
    ARCHITECTURE_SIDEBAR_MD,
    CONFIG_VERSION,
    DEVELOPER_NAME,
    DEVELOPER_TITLE,
    JUDGING_MESSAGE,
    LINKEDIN_URL,
    LOADING_MESSAGE,
    PAGE_ICON,
    PAGE_TITLE,
    PIPELINE_STEP_DRAFT,
    PIPELINE_STEP_JUDGE,
    PIPELINE_STEP_RAG,
    SESSION_DRAFT_VISIBLE,
    SESSION_JUDGE_SCORE,
    SESSION_JUDGE_TACTIC,
    SESSION_JUDGE_VERDICT,
    SESSION_LAST_MOCK_EMAIL,
    SESSION_RETRIEVED_POLICY,
)
from karenai.types import STEP_STATUS_VALUES, StepStatus

__version__ = "0.2.1"

__all__ = [
    "__version__",
    "AIRLINES",
    "APP_TAGLINE",
    "APP_TITLE",
    "ARCHITECTURE_SIDEBAR_MD",
    "CONFIG_VERSION",
    "DEVELOPER_NAME",
    "DEVELOPER_TITLE",
    "JUDGING_MESSAGE",
    "LINKEDIN_URL",
    "LOADING_MESSAGE",
    "PAGE_ICON",
    "PAGE_TITLE",
    "PIPELINE_STEP_DRAFT",
    "PIPELINE_STEP_JUDGE",
    "PIPELINE_STEP_RAG",
    "SESSION_DRAFT_VISIBLE",
    "SESSION_JUDGE_SCORE",
    "SESSION_JUDGE_TACTIC",
    "SESSION_JUDGE_VERDICT",
    "SESSION_LAST_MOCK_EMAIL",
    "SESSION_RETRIEVED_POLICY",
    "StepStatus",
    "STEP_STATUS_VALUES",
]
